version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/massari-server
permissions:
  - object: /var/www/html/massari-server/scripts
    pattern: "*.sh"
    owner: root
    mode: 777
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root
      timeout: 60
