version: 0.0
os: linux
files:
  - source: /
    destination: /usr/src/massari-server
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: root
      timeout: 300
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: root
      timeout: 60
