version: '3'
services:
  nignx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3030:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
    - /app/node_modules
    - .:/app
